steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcp-demo-proj-326120/pathwaytips-org/cloud-node-app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcp-demo-proj-326120/pathwaytips-org/cloud-node-app:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'pathwaytips-org', '--region=us-central1', '--platform=managed', '--image=gcr.io/gcp-demo-proj-326120/pathwaytips-org/cloud-node-app:$SHORT_SHA']
